FROM golang:1.25-alpine

ENV CGO_ENABLED=1
ENV GO111MODULE=on
ENV PATH="/root/go/bin:${PATH}"

RUN apk add --no-cache \
    build-base \     
    git \
    curl \
    sqlite \
    bash

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN mkdir -p /var/lib/mist

EXPOSE 8080

CMD ["air"]
